'use strict';

const mongoose = require('mongoose');

// ── Status timeline — one entry per status change ─────────────────────────────
const statusHistorySchema = new mongoose.Schema(
  {
    fromStatus: { type: String, default: '' }, // '' for the creation entry
    toStatus:   { type: String, required: true },
    changedBy:  { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    changedAt:  { type: Date, default: Date.now },
    note:       { type: String, trim: true, default: '' },
  },
  { _id: false } // entries are not individually addressable — no need for _id
);

const orderItemSchema = new mongoose.Schema(
  {
    product:    { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
    // ── Snapshot — values locked at checkout, independent of live product ──
    name:       { type: String, required: true },
    sku:        { type: String, required: true },
    image:      { type: String, default: '' },
    unitPrice:  { type: Number, required: true, min: 0 },
    quantity:   { type: Number, required: true, min: 1 },
    totalPrice: { type: Number, required: true, min: 0 },
  },
  { _id: false }
);

const ORDER_STATUSES   = ['pending_payment', 'pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded'];
const PAYMENT_STATUSES = ['unpaid', 'authorized', 'paid', 'failed', 'refunded', 'partially_refunded'];

// ── Payment history — one entry per payment-status change ─────────────────────
const paymentHistorySchema = new mongoose.Schema(
  {
    fromStatus:    { type: String, default: '' },
    toStatus:      { type: String, required: true },
    changedAt:     { type: Date, default: Date.now },
    changedBy:     { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    note:          { type: String, trim: true, default: '' },
    transactionId: { type: String, default: null },
    amount:        { type: Number, default: null }, // amount involved in this event (refund amount, etc.)
  },
  { _id: false }
);

const orderSchema = new mongoose.Schema(
  {
    orderNumber: { type: String, unique: true },

    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },

    items: { type: [orderItemSchema], required: true },

    shippingAddress: {
      street:  { type: String, required: true, trim: true },
      city:    { type: String, required: true, trim: true },
      zip:     { type: String, trim: true },
      country: { type: String, required: true, trim: true },
    },

    subtotal:       { type: Number, required: true, min: 0 },
    taxAmount:      { type: Number, required: true, min: 0 },
    shippingCost:   { type: Number, default: 0, min: 0 },

    // Coupon snapshot — locked at checkout, independent of live coupon state
    couponCode:     { type: String, default: null },
    couponType:     { type: String, enum: ['percentage', 'fixed', null], default: null },
    couponValue:    { type: Number, default: null },
    couponDiscount: { type: Number, default: 0, min: 0 },

    total:          { type: Number, required: true, min: 0 },

    status: {
      type: String,
      enum: { values: ORDER_STATUSES, message: 'Invalid order status' },
      default: 'pending_payment',
    },
    paymentStatus: {
      type: String,
      enum: { values: PAYMENT_STATUSES, message: 'Invalid payment status' },
      default: 'unpaid',
    },
    paymentRef:     { type: String, default: null },   // Stripe PaymentIntent ID (stub)
    expiresAt:      { type: Date,   default: null },   // payment deadline for pending_payment orders
    refundedAmount: { type: Number, default: 0, min: 0 }, // cumulative amount refunded so far

    paymentHistory: { type: [paymentHistorySchema], default: [] },

    notes: { type: String, trim: true },

    // Full lifecycle timeline — appended on every status change
    statusHistory: { type: [statusHistorySchema], default: [] },
  },
  {
    timestamps: true,
    toJSON:   { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ── Computed read-only virtual — never stored ─────────────────────────────────
// 'active'    → payment window open (pending_payment, unpaid, expiresAt in future)
// 'expired'   → window closed but order not yet cancelled by the job
// 'completed' → payment succeeded or order no longer in pending_payment state
orderSchema.virtual('paymentReservationStatus').get(function () {
  if (this.paymentStatus === 'paid')     return 'completed';
  if (this.status !== 'pending_payment') return 'completed';
  if (this.expiresAt && this.expiresAt < new Date()) return 'expired';
  return 'active';
});

// orderNumber is generated by the service (with collision-retry) before save.
// The unique index below is the enforcement layer; the model does not auto-generate it.

// Compound indexes aligned to actual query patterns:
//   listMyOrders  → filter user, sort createdAt
//   listAllOrders → filter status, sort createdAt
//   getOrder      → orderNumber lookup
orderSchema.index({ user: 1, createdAt: -1 });
orderSchema.index({ status: 1, createdAt: -1 });
orderSchema.index({ paymentStatus: 1 });
orderSchema.index({ status: 1, expiresAt: 1 }); // for expiry cancellation job
orderSchema.index({ createdAt: -1 }); // unfiltered admin list

module.exports = mongoose.model('Order', orderSchema);
module.exports.ORDER_STATUSES = ORDER_STATUSES;
