#!/usr/bin/env node
'use strict';

/**
 * Removes mock/seed products from the database, keeping only real imported
 * KSP-style products identified by their SKU prefix.
 *
 * Safe: touches only the products collection. Users, orders, categories,
 * coupons, reviews, and notifications are never modified.
 *
 * How real products are identified:
 *   Each real catalog importer assigns a fixed SKU prefix to its category.
 *   Any product whose SKU does NOT start with a prefix in REAL_PREFIXES is
 *   considered a mock product generated by the general seed.js script.
 *
 * How mock products are identified:
 *   Mock products use generic prefixes (TV-LAP, TV-PHN, TV-TAB, TV-GAM,
 *   TV-SPK, TV-STO, TV-NET, TV-SMH, TV-ACC, etc.) produced by seed.js.
 *   They do not appear in REAL_PREFIXES and will be deleted.
 *
 * How Docker / local dev resolve their Mongo connection string:
 *   This script does NOT override NODE_ENV. It loads .env via dotenv for
 *   local development (where NODE_ENV is typically unset or 'development')
 *   so db.js selects MONGO_URI_DEV. Inside a Docker container NODE_ENV is
 *   already 'production' (injected by docker-compose.yml), so db.js picks
 *   MONGO_URI_PROD — also injected by compose as mongodb://mongodb:27017/techvault.
 *   dotenv.config() is a no-op in Docker because /app/.env does not exist
 *   in the image, which is intentional.
 *
 * Usage (local dev):
 *   node server/scripts/cleanupMockProducts.js
 *   npm run cleanup:mock-products
 *
 * Usage (Docker — stack must be running):
 *   docker compose exec backend node server/scripts/cleanupMockProducts.js
 */

const path = require('path');

// Load .env for local dev; in Docker, env vars are already present.
require('dotenv').config({ path: path.join(__dirname, '../../.env') });

const { connectDB } = require('../config/db');
const mongoose      = require('mongoose');
const Product       = require('../models/Product');

// ─── Console colours ─────────────────────────────────────────────────────────
const c = {
  green:  (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  red:    (s) => `\x1b[31m${s}\x1b[0m`,
  bold:   (s) => `\x1b[1m${s}\x1b[0m`,
  dim:    (s) => `\x1b[2m${s}\x1b[0m`,
  cyan:   (s) => `\x1b[36m${s}\x1b[0m`,
};
const log  = (msg) => console.log(c.green('✓') + ' ' + msg);
const warn = (msg) => console.log(c.yellow('⚠') + ' ' + msg);
const fail = (msg) => console.log(c.red('✗') + ' ' + msg);
const info = (msg) => console.log(c.dim('  ' + msg));
const head = (msg) => console.log('\n' + c.bold(c.cyan(msg)));

// ─── SKU prefixes that belong to real imported products ───────────────────────
// Each entry maps to one importer script. Add a new prefix here whenever a new
// real catalog importer is written. Never add prefixes for mock/seed data.
//
//   TV-KB-   seedKeyboards.js    server/data/keyboards/
//   TV-MN-   seedMonitors.js     server/data/monitors/
//   TV-MS-   seedMice.js         server/data/mice/
//   TV-PC-   seedDesktops.js     server/data/desktops/
//   TV-HPH-  seedHeadphones.js   server/data/headphones/
const REAL_PREFIXES = [
  'TV-KB-',   // Keyboards
  'TV-MN-',   // Monitors
  'TV-MS-',   // Mice
  'TV-PC-',   // Desktops / PCs
  'TV-HPH-',  // Headphones
];

const buildFilter = () => {
  // Match any product whose SKU does NOT start with a real prefix.
  const exclude = REAL_PREFIXES.map((p) => new RegExp(`^${p}`, 'i'));
  return { sku: { $not: { $in: exclude } } };
};

const run = async () => {
  head('TechVault — Mock Product Cleanup');

  const env = process.env.NODE_ENV || 'development';
  info(`NODE_ENV : ${env}`);
  info(`Keeping  : ${REAL_PREFIXES.join(', ')}`);

  await connectDB();

  const filter = buildFilter();

  const totalBefore  = await Product.countDocuments({});
  const mockCount    = await Product.countDocuments(filter);
  const keepCount    = totalBefore - mockCount;

  head('Before');
  info(`Total products   : ${totalBefore}`);
  info(`Real (keeping)   : ${keepCount}  (${REAL_PREFIXES.join(', ')})`);
  info(`Mock (deleting)  : ${mockCount}`);

  if (mockCount === 0) {
    log('Nothing to delete — database is already clean.');
    await mongoose.connection.close();
    return;
  }

  // ── Preview first 10 SKUs that will be removed ─────────────────────────────
  const preview = await Product.find(filter, 'sku name').limit(10).lean();
  head('Sample of products to be deleted');
  preview.forEach((p) => info(`  ${p.sku.padEnd(20)} ${p.name}`));
  if (mockCount > 10) info(`  … and ${mockCount - 10} more`);

  // ── Delete ──────────────────────────────────────────────────────────────────
  head('Deleting');
  const result = await Product.deleteMany(filter);

  const totalAfter = await Product.countDocuments({});

  head('After');
  info(`Products deleted : ${result.deletedCount}`);
  info(`Products remain  : ${totalAfter}`);

  if (result.deletedCount === mockCount) {
    log(`Done — removed ${result.deletedCount} mock product(s), ${totalAfter} real product(s) remain.`);
  } else {
    warn(`Expected to delete ${mockCount} but deleted ${result.deletedCount}. Check for concurrent writes.`);
  }

  await mongoose.connection.close();
};

run().catch((err) => {
  fail(`Fatal: ${err.message}`);
  process.exit(1);
});
